config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products, only: [] do
      resources :sale_prices
    end
  end
end

app/models/spree/sale_price.rb
module Spree
  class SalePrice < ActiveRecord::Base

    belongs_to :price, class_name: "Spree::Price"
    delegate_belongs_to :price, :currency

    has_one :variant, through: :price

    has_one :calculator, class_name: "Spree::Calculator", as: :calculable, dependent: :destroy
    validates :calculator, presence: true
    accepts_nested_attributes_for :calculator

    scope :active, -> { where(enabled: true).where('(start_at <= ? OR start_at IS NULL) AND (end_at >= ? OR end_at IS NULL)', Time.now, Time.now) }

    before_destroy :touch_product
    # TODO make this work or remove it
    #def self.calculators
    #  Rails.application.config.spree.calculators.send(self.to_s.tableize.gsub('/', '_').sub('spree_', ''))
    #end

    def calculator_type
      calculator.class.to_s if calculator
    end

    def calculated_price
      calculator.compute self
    end

    def enable
      update_attribute(:enabled, true)
    end

    def disable
      update_attribute(:enabled, false)
    end

    def active?
      Spree::SalePrice.active.include? self
    end

    def start(end_time = nil)
      end_time = nil if end_time.present? && end_time <= Time.now # if end_time is not in the future then make it nil (no end)
      attr = { end_at: end_time, enabled: true }
      attr[:start_at] = Time.now if self.start_at.present? && self.start_at > Time.now # only set start_at if it's not set in the past
      update_attributes(attr)
    end

    def stop
      update_attributes({ end_at: Time.now, enabled: false })
    end

    # Convenience method for displaying the price of a given sale_price in the table
    def display_price
      Spree::Money.new(value || 0, { currency: price.currency })
    end

    protected
      def touch_product
        self.variant.product.touch
      end

  end
end

app/controllers/spree/admin/sale_prices_controller.rb
module Spree
  module Admin
    class SalePricesController < BaseController

      before_filter :load_product

      respond_to :js, :html

      def index
        @sale_prices = @product.sale_prices
      end

      def create
        @sale_price = @product.put_on_sale params[:sale_price][:value], sale_price_params
        respond_with(@sale_price)
      end

      def destroy
        @sale_price = Spree::SalePrice.find(params[:id])
        @sale_price.destroy
        respond_with(@sale_price)
      end

      private

      def load_product
        @product = Spree::Product.find_by(slug: params[:product_id])
        redirect_to request.referer unless @product.present?
      end

      def sale_price_params
        params.require(:sale_price).permit(
            :id,
            :value,
            :currency,
            :start_at,
            :end_at,
            :enabled
        )
      end
    end
  end
end

app/views/spree/admin/sale_prices/_sale_price.html.slim
tr data-hook="products_row" id = spree_dom_id(sale_price) class = "spree-product-sale-price"
  td.align-center = sale_price.active? ? 'Yes' : ''
  td = sale_price.display_price.to_html
  td = (l sale_price.start_at ) if sale_price.start_at
  td = (l sale_price.end_at) if sale_price.end_at
  td.align-center = sale_price.enabled
  td.actions
    = link_to_delete sale_price, {url: admin_product_sale_price_url(product, sale_price.id), no_text: true}

app/views/spree/admin/sale_prices/_table.html.slim
table.index#product_sale_prices data-hook="sale_price_table"
  colgroup
    col
    col
    col style="width: 30%"
    col style="width: 30%"
    col
    col
  thead
    tr data-hook="products_header"
      th = Spree.t('sale_price_active')
      th = Spree.t('sale_price')
      th = Spree.t('sale_price_start_at')
      th = Spree.t('sale_price_end_at')
      th = Spree.t('sale_price_enabled')
      th.actions
  tbody
    = render partial: "sale_price", collection: product.master.sale_prices, locals: {product: product}

app/views/spree/admin/sale_prices/create.js.erb
$('table#product_sale_prices').replaceWith('<%= j render partial: "table", locals: {product: @product} %>');

app/views/spree/admin/sale_prices/destroy.js.erb
$('td.spree-product-sale-price#<%= j spree_dom_id(@sale_price) %>').remove();

app/views/spree/admin/sale_prices/index.html.slim
= render :partial => 'spree/admin/shared/product_sub_menu'
= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Product Sale Prices"}

= csrf_meta_tag

#add-line-item
  fieldset
    legend align="center" = Spree.t('add_product_sale_prices')

    = form_for [:admin, @product, Spree::SalePrice.new], remote: true do |f|
      .row
        .columns.three
          = label_tag t('original_price')
          = text_field_tag '', @product.original_price.to_f, disabled: true

      .row
        .columns.three
          = f.label :value, t('sale_price_amount')
          = f.text_field :value
        .columns.three
          = f.label :currency, t('sale_price_currency')
          = f.select :currency, options_for_select(supported_currencies_for_sale_price)

      .row
        .columns.three
          = f.label :start_at, t('sale_price_start_at')
          = f.text_field :start_at, class: "datepicker"
        .columns.three
          = f.label :end_at, t('sale_price_end_at')
          = f.text_field :end_at, class: "datepicker"
        .columns.three
          = f.label :submit, style: 'visibility: hidden;'
          = f.submit "Add Sale Price"

#product-sale-prices-table
  = render partial: "table", locals: { product: @product }